DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS rsvps CASCADE;
DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS time_slots CASCADE;
DROP TABLE IF EXISTS time_selections CASCADE;


CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  name TEXT  NOT NULL,
  email TEXT NOT NULL
);


CREATE TABLE events (
  id SERIAL PRIMARY KEY NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  address TEXT NOT NULL,
  admin_token TEXT NOT NULL,
  guest_token TEXT NOT NULL,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE
);


CREATE TABLE rsvps (
  id SERIAL PRIMARY KEY NOT NULL,
  availability BOOLEAN NOT NULL,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  event_id  INTEGER NOT NULL REFERENCES events(id) ON DELETE CASCADE
);

CREATE TABLE time_slots (
  id SERIAL PRIMARY KEY NOT NULL,
  start_date_time TIMESTAMP,
  end_date_time TIMESTAMP,
  event_id INTEGER NOT NULL REFERENCES events(id) ON DELETE CASCADE
);


CREATE TABLE time_selections (
  id SERIAL PRIMARY KEY NOT NULL,
  time_slot_id INTEGER NOT NULL REFERENCES time_slots(id) ON DELETE CASCADE,
  rsvp_id INTEGER NOT NULL REFERENCES rsvps(id) ON DELETE CASCADE
);
